// eslint-disable-next-line
export const FOLDERS_ACTIONS = {
  FOLDERS_INIT: 'FOLDERS_INIT',
  FOLDERS_SAVE: 'FOLDERS_SAVE',
  FOLDERS_SET: 'FOLDERS_SET',
  FOLDERS_ADD: 'FOLDERS_ADD',
  FOLDERS_UPDATE: 'FOLDERS_UPDATE',
  FOLDERS_REMOVE: 'FOLDERS_REMOVE',
  FOLDERS_CLEAR: 'FOLDERS_CLEAR',
};
