// eslint-disable-next-line
export const MEDIAS_ACTIONS = {
  MEDIAS_SET: 'MEDIAS_SET',
  MEDIAS_ADD: 'MEDIAS_ADD',
  MEDIAS_UPDATE: 'MEDIAS_UPDATE',
  MEDIAS_REMOVE: 'MEDIAS_REMOVE',
  MEDIAS_CLEAR: 'MEDIAS_CLEAR',
  MEDIA_SET: 'MEDIA_SET',
  MEDIA_CLEAR: 'MEDIA_CLEAR',
};

