// eslint-disable-next-line
export const GALLERIES_ACTIONS = {
    GALLERIES_SET: 'GALLERIES_SET',
    GALLERIES_ADD: 'GALLERIES_ADD',
    GALLERIES_UPDATE: 'GALLERIES_UPDATE',
    GALLERIES_REMOVE: 'GALLERIES_REMOVE',
    GALLERIES_CLEAR: 'GALLERIES_CLEAR'
  };
  
  